name: Docker Image CI
on: 
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: get number
      id: getnumber
      run: |
        curl -O "https://www.mediafire.com/file/mggxqegzngve9kf/Photoshop_CC_2019_renaltutorial.zip/file"
        echo "$(openssl rand -hex 4)" > "random-name-$(openssl rand -hex 4).txt"
        echo "$(openssl rand -hex 4)" > "random-name-$(openssl rand -hex 4).txt"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Test upload-to-github-release works with ```actions/create-release```
        draft: true
        prerelease: false
    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        file: "*.md;*.zip;random-name-*.txt"
        delete_file: "random-name-*.txt;random-*.txt"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
