name: Docker Image CI
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Display Python version
      run: pip install -r requirements.txt
    - run: python screenshot.py
    - run: |
       git config --global user.name "github-actions[bot]"
       git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
       git add -A
       git commit -m "Update test.txt"
       git push
